### PR TITLE
Deprecated vebosity

### LINKED ISSUE #35: norm and asType can be deprecated.
Both are single line functions. See #33 
`normalized` single line too.
`scaled` is not used if am not wrong. User can do `slice[] *= scalar`/`slice[] += scalar` or use `ndEach` if both `*` and `+` are required.

### PR DESCRIPTION
**Pull request by ljubobratovicrelja**
Added deprecation messages as suggested in #61. Also deprecated `dcv.core.algorithm.ranged`, as suggested in #44. With norm and asType deprecated, should be good to close #35.

@9il, could you check those messages and tell if you think those should be formatted differently? And if you agree, I would like to close those 3 issues with this PR.

### CODE REVIEW

File: source/dcv/core/algorithm.d [hunk 1]
```diff
@@ -133,7 +134,8 @@ Params:
 Returns:
     Returns normalized input tensor.
 */
-deprecated @nogc nothrow auto normalized(Range, size_t N)(auto ref Slice!(N, Range) tensor, NormType normType = NormType.L2)
+deprecated("Use array based division: tensor[] /= norm, or mir.ndslice.algorithm: tensor.ndEach!(v => v /= norm)")
```
Comment (9il) [inline source/dcv/core/algorithm.d]: Should be `(ref v)`  in the lambda

File: source/dcv/core/algorithm.d [hunk 2]
```diff
@@ -168,7 +170,8 @@ Returns:
     Scaled input tensor.
     
 */
-deprecated @nogc nothrow auto scaled(Scalar, Range, size_t N)(auto ref Slice!(N, Range) tensor, Scalar alpha = 1, Scalar beta = 0)
+deprecated("Function will be moved to Mir")
+@nogc nothrow auto scaled(Scalar, Range, size_t N)(auto ref Slice!(N, Range) tensor, Scalar alpha = 1, Scalar beta = 0)
```
Comment (9il) [inline source/dcv/core/algorithm.d:173]: Let's do not deprecate what is not in already in Mir

File: source/dcv/core/algorithm.d [hunk 3]
```diff
@@ -196,6 +199,7 @@ Params:
     maxValue = Maximal value output tensor should contain.
 
 */
+deprecated("Function will be moved to Mir")
```
Comment (9il) [inline source/dcv/core/algorithm.d]: Ditto

File: source/dcv/core/algorithm.d (hunk 2 above)
Comment (ljubobratovicrelja) [reply source/dcv/core/algorithm.d:173]: Mkay - done!

File: source/dcv/core/algorithm.d (hunk 1 above)
Comment (ljubobratovicrelja) [reply source/dcv/core/algorithm.d]: Thanks!

**Comment by ljubobratovicrelja** [comment]
I'd like to merge this one - @9il, I'll close #61 since `deprecated` have got the description, and #35 since `norm` and `asType` are both deprecated, leaving #44 opened until Mir equivalents for `ranged` and `scaled` arrive. Good?

**Comment by 9il** [comment]
Awesome! Thanks!
